### ISSUE TITLE
Vue suggests to use Vitest instead of Jest

### ISSUE THREAD

**Issue by Vinccool96** [GLO3102/vue-starter#17]
Source: https://vuejs.org/guide/scaling-up/testing.html#recommendation

Explanation provided by Vue (taken from the source):

> Since the official setup created by `create-vue` is based on [Vite](https://vitejs.dev/), we recommend using a unit testing framework that can leverage the same configuration and transform pipeline directly from Vite. [Vitest](https://vitest.dev/) is a unit testing framework designed specifically for this purpose, created and maintained by Vue / Vite team members. It integrates with Vite-based projects with minimal effort, and is blazing fast.

**Comment by vseguin** [comment]
Updated to latest, thanks!
